-- ============================================================
-- SolarFlow Pro v2 — Additional Schema (run AFTER v1 schema)
-- ============================================================

-- ── Roof analysis cache ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.roof_analysis_cache (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  contact_id   uuid NOT NULL REFERENCES public.contacts(id) ON DELETE CASCADE,
  address      text NOT NULL,
  country      text NOT NULL DEFAULT 'BE',
  result       jsonb NOT NULL,    -- full RoofAnalysis dataclass as JSON
  analysed_at  timestamptz DEFAULT now(),
  UNIQUE (contact_id)
);

-- RLS: agents can read their own org's cached analyses
ALTER TABLE public.roof_analysis_cache ENABLE ROW LEVEL SECURITY;
CREATE POLICY "roof_cache_org" ON public.roof_analysis_cache
  FOR ALL USING (
    contact_id IN (
      SELECT id FROM public.contacts WHERE org_id = auth_org_id()
    )
  );

-- ── Savings pages ────────────────────────────────────────────
-- Public pages generated by the ROI calculator
CREATE TABLE IF NOT EXISTS public.savings_pages (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  token          text NOT NULL UNIQUE,
  contact_id     uuid REFERENCES public.contacts(id),
  org_id         uuid NOT NULL REFERENCES public.organizations(id),
  agent_id       uuid NOT NULL REFERENCES public.user_profiles(id),
  campaign_id    uuid REFERENCES public.campaigns(id),
  roi_data       jsonb NOT NULL,
  prospect_name  text,
  address_display text,
  created_at     timestamptz DEFAULT now(),
  expires_at     timestamptz DEFAULT now() + interval '30 days',
  viewed         boolean DEFAULT false,
  last_viewed_at timestamptz,
  view_count     int DEFAULT 0
);

-- Public read by token (no auth needed — prospect opens the link)
ALTER TABLE public.savings_pages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "savings_public_read" ON public.savings_pages
  FOR SELECT USING (true);   -- public — token acts as the secret
CREATE POLICY "savings_org_write" ON public.savings_pages
  FOR ALL USING (org_id = auth_org_id());

-- ── Add WhatsApp column to call_logs ─────────────────────────
ALTER TABLE public.call_logs
  ADD COLUMN IF NOT EXISTS whatsapp_sent boolean DEFAULT false;

-- ── WhatsApp message log (optional — useful for debugging) ───
CREATE TABLE IF NOT EXISTS public.whatsapp_log (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id      uuid NOT NULL REFERENCES public.organizations(id),
  contact_id  uuid REFERENCES public.contacts(id),
  agent_id    uuid REFERENCES public.user_profiles(id),
  outcome     text,
  template    text,
  phone       text,
  sent        boolean DEFAULT false,
  error       text,
  sent_at     timestamptz DEFAULT now()
);

ALTER TABLE public.whatsapp_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "wa_log_org" ON public.whatsapp_log
  FOR ALL USING (org_id = auth_org_id());
